name: "Kotlin CI/CD Tests"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types:
      - submitted

jobs:
    build:

      name: Test and Build
      runs-on: ubuntu-latest

      # Checkout the code repository
      steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      # Display the variables saved for build
      - name: echo Job env vars
        run: env

      # Fetch dependancies or get from cache
      - name: Fetch Dependancies
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      # Compile the java code to byte code
      - name: Build the jar file
        run: ./gradlew clean build --no-daemon

      # Running ktlint for code linting
      - name: Run ktlint with reviewdog
        uses: ScaCap/action-ktlint@1.4
        with:
          # GITHUB_TOKEN
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Report level for reviewdog [info,warning,error]
          level: info
          reporter: github-pr-check
          # Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
          # Default is added.

          filter_mode: added
          # Exit code for reviewdog when errors are found [true,false]
          # Default is `false`.
          fail_on_error: true

      # Running detekt for code smells
      - name: Static code analysis with detekt
        run: ./gradlew detekt

      # Upload code analysis report to github
      - name: Upload Static code report to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          ref: "refs/heads/$GITHUB_REF_NAME"
          sha: ${{ github.sha }}
          sarif_file: ${{ github.workspace }}/build/reports/detekt/detekt.sarif

      # Generating unit test code coverage
      - name: Adding test coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

      # Docker build and push to docker registry
      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.8
        if: github.event_name == 'pull_request' && github.event.action == 'closed' # Only build image if the PR has actually been closed
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/demoapp
          tags: $(git rev-parse --short HEAD)
          registry: docker.io
          dockerfile: Dockerfile.ci
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          pushImage: true
