name: "Kotlin CI/CD Tests"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # schedule:
  #   - cron: '45 12 * * 5'

jobs:
    build:

      name: Publish docker image to ecr
      runs-on: ubuntu-latest


      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: echo branch names
        run: |
          echo ${GITHUB_HEAD_REF}
          echo ${{github.base_ref}}
          echo ${{github.ref}}
          echo ${GITHUB_REF##*/}
          echo "TF_WORKSPACE=${GITHUB_HEAD_REF##*/}"