name: "Kotlin CI/CD Tests"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # schedule:
  #   - cron: '45 12 * * 5'

jobs:
    build:

      name: Test and Build
      runs-on: ubuntu-latest


      steps:

      - name: Code Checkout
        uses: actions/checkout@v3


      - name: Compute release hash
        id: release_hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: echo Job env vars
        run: |
          echo ${GITHUB_HEAD_REF}
          echo ${{github.base_ref}}
          echo ${{github.ref}}
          echo ${GITHUB_REF##*/}
          echo "TF_WORKSPACE=${GITHUB_HEAD_REF##*/}"
          echo ${{ steps.release_hash.outputs.sha_short }}

      - name: Running Test and Build
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon


      - name: Adding test coverage to Pull request
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60